name: Postman Tests Workdflow
on:
  push: 
    branches: 
      - main
  workflow_dispatch:
    inputs: 
      environment:
        description: 'Choose Env'
        required: true
        default: staging

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
       - name: Use input
         run: echo Running ${{ github.event.inputs.environment }}
  
  
