name : Postman Tests

on:
  push: #Event driven!!! Push something into main branch
    branches: [main]
  workflow_dispatch: #Manual Play Button


jobs:
  run-tests:
    runs-on : ubuntu-latest

    steps:
    
      - name : Checkout the code #Bring our Postman Collection on the newly create VM
        uses: actions/checkout@v4.2.2

      - name : Install Node js
        uses: actions/setup-node@v3.9.1
        with: 
          node-version: '22'

      - name: Install newman and html extra
        run: | 
              npm install -g newman
              npm install -g newman-reporter-htmlextra
      

      - name: Run the Postman Collection
        run: | 
              newman run 'Inwarranty-flow Collection Copy.postman_collection.json' \ 
              -e QA.postman_environment.json \
              -r cli,htmlextra \
              -d testdata.csv

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: Download Report
          path: newman/*.html




        
    
  
