name: GitHub Actions Demo
on: 
    workflow_dispatch: # Allows manual run from GitHub UI
jobs:
  run-postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: 🧾 Checkout repo
        uses: actions/checkout@v3

      - name: 🔧 Install Newman and Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: 🧪 Run Postman Tests
        run: |
          newman run "Inwarranty.postman_collection.json" \
            -e "QA.postman_environment.json" \
            --reporters cli,htmlextra \
